sonar.projectKey=Renard
sonar.projectName=Renard
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.newCode.referenceBranch=main
sonar.host.url=http://localhost:9000
sonar.login=sqa_7a5193c76d1ba34c1403f208c112686909a1c700
